version: "3.9"

services:
  web:
    build: .
    container_name: django-dev
    ports:
      - "8000:8000"
    volumes:
      - ./djangowebsite:/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      -.secret.env

  